#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
    SP_NAME_DAD,
    SP_NAME_BRINEY,
    SP_NAME_NURSE,
    SP_NAME_STEVEN,
    SP_NAME_DOCK,
    SP_NAME_STERN,
    SP_NAME_ARCHIE,
    SP_NAME_SHELLY,
    SP_NAME_MATT,
    SP_NAME_MAXIE,
    SP_NAME_TABITHA,
    SP_NAME_COURTNEY, // Unused in Emerald
    SP_NAME_SCOTT,
    SP_NAME_WALLACE,
    SP_NAME_COZMO,
    SP_NAME_BIRCH,
    SP_NAME_TRICK,
    SP_NAME_RIVAL,
    SP_NAME_WALLY,
    SP_NAME_RYDEL,
    SP_NAME_ANNA,
    SP_NAME_MEG,
    SP_NAME_NORMAN,
    SP_NAME_TATE,
    SP_NAME_LIZA,
    SP_NAME_TATE_LIZA,
    SP_NAME_KIRI,
    SP_NAME_WATTSON,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
